title: Hustle up the Hill for the Homeless
description: > # this means to ignore newlines until "baseurl:"
  Hustle Up The Hill
  For The Homeless
  May 21, 2017
  9 am & 10 am
  Blackwell Forest Preserve - Mt. Hoy
baseurl: "/hustle" # the subpath of your site, e.g. /blog
url: "swdelaney2.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "/css/2017_style/img/icon-large.png"

social:
  name: Bridge Communities
  link: "https://www.facebook.com/bridge.communities/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2017_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/bridge.communities/
  - title: twitter
    url: https://twitter.com/bridgedupage

# Build settings
markdown: kramdown
permalink: pretty
